# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b51771209bd858c553f15947e9248fe3e9fec50793ab65f50d0ee93fb253a6abb0372460e4fb33b86df7fbc5dd94acdd15bef47c97bae1e7bb9a8a7c925da39

test:
  secret_key_base: a7d37c845827faba2fcf02807654d50027457462e18b30bc9b1de90a01adcbad64858694558f0fe29e613355a7312b674fafd7a259aa288c8e4939d85b8a0b2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
